### ISSUE TITLE
[BUG]: Error when running treemap

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1136]
When working in the GUI for visualization tools, when running visualize categorical data in the tree map option i get the following error:
![viz gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/c2856949-7672-4f43-98f1-8427f4d3bf81)
![error line](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/8b6d2735-1ac5-40fd-8fee-e3550ed23ac5)

**Comment by Emory-NLP** [comment]
Oh dear. An old test function call left there. You can open the file data_visualization_main.py (in the scr folder) with either a Python editor or any text editor such as notepad, search for RF_charts, remove that line and save. It will be corrected with the next release.

**Comment by kaavyamuthuganesan** [comment]
thank you

**Comment by kaavyamuthuganesan** [comment]
now i am getting the following error when i run treemap:
Traceback (most recent call last):
  File "C:\Users\kaavy\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "data_visualization_main.py", line 226, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "data_visualization_main.py", line 193, in run
    outputFiles = charts_util.treemaper(inputFilename, outputFilename,
  File "C:\Program Files\NLP-Suite-current-stable\src\charts_util.py", line 1347, in treemaper
    fig=px.treemap(data,path=[px.Constant('Total Frequency'),'interest',csv_file_field])
  File "C:\Users\kaavy\anaconda3\lib\site-packages\plotly\express\_chart_types.py", line 1591, in treemap
    return make_figure(
  File "C:\Users\kaavy\anaconda3\lib\site-packages\plotly\express\_core.py", line 2078, in make_figure
    args = process_dataframe_hierarchy(args)
  File "C:\Users\kaavy\anaconda3\lib\site-packages\plotly\express\_core.py", line 1702, in process_dataframe_hierarchy
    df_tree["labels"] = dfg[level].copy().astype(str)
  File "C:\Users\kaavy\anaconda3\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\kaavy\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: '1-grams_path_copy'
