### ISSUE TITLE
[BUG]: Visualization GUI (Plotly)

### ISSUE THREAD

**Issue by angelinacchen** [NLP-Suite/NLP-Suite#1190]
<img width="1345" alt="Screen Shot 2023-09-29 at 5 16 23 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/cde04e61-2cbb-49da-aee7-bb431af53cee">

<img width="566" alt="Screen Shot 2023-09-29 at 5 17 53 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/06d665cb-db7d-4695-8e55-bc6cc68dbfa5">

All the visualization GUIs for Plotly including Boxplot return the save error in Terminal. The corpus I am using is the Novel Corpus for Group 5. I have the CoNLL table as my csv input file.

**To Reproduce**
1. Go to a Plotly Visualization Too
2. Click on Run
3. Scroll down to the bottom of the terminal

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Release Version 4.0.7

**Additional context**
I see this error with the other Plotly visualization as well such as Treemap, Sunburst pie chart, Sankey flow chart.

**Comment by bianshuyang** [comment]
Hi Angelina, Can you send an attachment here of the file you are operating on? Tks.

**Comment by bianshuyang** [comment]
Note: Please do not respond by emory email because it will otherwise block my access to see the file. Instead, upload an attachment as you reply here in thread.

**Comment by angelinacchen** [comment]
Hi Shuyang,

This is the file I am operating on:
 NLP_CoreNLP_Dir_Corpus_nn_CoNLL.csv
<https://drive.google.com/file/d/1w6et7PFTRPivDogl8qgJz1ww_o8-TWh4/view?usp=drive_web>
Thank you!

**Comment by bianshuyang** [comment]
I don't have access, please do give me access. Alternatively, **drag** the csv into the "Leave a comment" window in the **github webpage (NOT YOUR EMAIL)**  to upload the file. It should take less than 1 minute.

ALternatively, your TAs has suggested some possible approaches:
`Apparently this is a solution to Angelina's error: (link)[https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte]`

<img width="746" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/c6bf6a00-6f97-49e2-8166-7c26aba335c9">

**Comment by bianshuyang** [comment]
You may want to select all and then: 
https://www.charset.org/utf8-to-latin-converter
Convert utf-8 to latin encoding
If you know some coding, you can play around with encoding via things documented here:
https://www.charset.org/programming/converting-latin-to-utf8

**Comment by Emory-NLP** [comment]
Angelina, you need to copy and paste the set of error lines that you get in terminal or there is no way to know which lines of codes provoke the error. I do not get that error, incidentally.

**Comment by angelinacchen** [comment]
This is the csv file I used: 
[NLP_CoNLL_SpaCy_Dir_newspaperArticles.csv](https://github.com/NLP-Suite/NLP-Suite/files/12795457/NLP_CoNLL_SpaCy_Dir_newspaperArticles.csv)

Here are the error lines I received when trying to run Boxplot GUI:
<img width="1298" alt="Screen Shot 2023-10-03 at 2 00 29 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/8a422642-533a-422c-97bd-dc1f89e3ca5e">

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/angelinachen/opt/anaconda3/envs/NLP/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "data_visualization_2_main.py", line 113, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "data_visualization_2_main.py", line 67, in run
    outputfilename = charts_util.boxplot(inputFilename, outputFilename, csv_field_var,
  File "/Users/angelinachen/Desktop/NLP-Suite-current-stable/src/charts_util.py", line 1162, in boxplot
    data=pd.read_csv(data)
  File "/Users/angelinachen/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/angelinachen/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/angelinachen/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/angelinachen/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/Users/angelinachen/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 550, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 639, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2021, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 12584: invalid continuation byte

**Comment by Emory-NLP** [comment]
OK, I see the error. I think you should rerun the CoreNLP parser and see where that is giving errors. Will send file by email.

**Comment by angelinacchen** [comment]
<img width="1343" alt="Screen Shot 2023-10-04 at 1 04 56 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/7823dab9-e040-48a2-a052-a423cd073ebd">
I am trying to open the parser GUI but after following the instructions in the pop, I'm still getting the error that Stanza isn't found.
