### ISSUE TITLE
Error when running Nominalization GUI

### ISSUE THREAD

**Issue by lydianneking** [NLP-Suite/NLP-Suite#1262]
**Screenshot of NLP Suite:** 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143012998/8367efdd-e120-42b3-b9ab-8349a8a8a4c0)

**When I click to open the nominalization GUI, it won't open. I get this error:**
Warming up PyWSD (takes ~10 secs)... Traceback (most recent call last):
  File "nominalization_main.py", line 15, in <module>
    if IO_libraries_util.install_all_Python_packages(GUI_util.window,"Nominalization",['tkinter','nltk','pywsd','wn','csv','re','os','collections'])==False:
  File "/Users/lydiaking/Downloads/NLP-Suite-current-stable/src/IO_libraries_util.py", line 70, in install_all_Python_packages
    i = __import__(module, fromlist=[''])
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/pywsd/__init__.py", line 34, in <module>
    simple_lesk('This is a foo bar sentence', 'bar')
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/pywsd/lesk.py", line 241, in simple_lesk
    ambiguous_word = lemmatize(ambiguous_word, pos=pos)
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/pywsd/utils.py", line 92, in lemmatize
    pos = pos if pos else penn2morphy(pos_tag([ambiguous_word])[0][1],
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/nltk/tag/__init__.py", line 165, in pos_tag
    tagger = _get_tagger(lang)
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/nltk/tag/__init__.py", line 107, in _get_tagger
    tagger = PerceptronTagger()
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/nltk/tag/perceptron.py", line 167, in __init__
    find("taggers/averaged_perceptron_tagger/" + PICKLE)
  File "/Users/lydiaking/anaconda3/envs/NLP/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

  Searched in:
    - '/Users/lydiaking/nltk_data'
    - '/Users/lydiaking/anaconda3/envs/NLP/nltk_data'
    - '/Users/lydiaking/anaconda3/envs/NLP/share/nltk_data'
    - '/Users/lydiaking/anaconda3/envs/NLP/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

I'm running it on NLP Suite 4.3.3, and I have a MacOS Big Sur, Version 11.7.6

**Comment by bianshuyang** [comment]
I have been informed by Professor that this was fixed just now. You may try again immediately as it's been pushed to current-stable.

**Comment by kaavyamuthuganesan** [comment]
I am facing the same issue using ver 4.4.0

**Comment by kaavyamuthuganesan** [comment]
ok i seem to have fixed the issue by looking at issue 1271
