### ISSUE TITLE
Unable to generate wordcloud output

### ISSUE THREAD

**Issue by AngelinaYing** [NLP-Suite/NLP-Suite#1372]
I followed the instructions in the rubric and tried to run wordcloud. In the output directory I can only see an empty folder. Below is the error message in the terminal. Thanks!

Started running STANZA and wordcloud at 15:25.

Please, be patient. Depending upon the number of documents processed this may take a few minutes.

Processing file 1/5 Conrad_Lord Jim.txt
Processing file 2/5 Fitzgerald_The Great Gatsby.txt
Processing file 3/5 Ford_The Good Soldier.txt
Processing file 4/5 Forster_A Room with a View.txt
Processing file 5/5 James_The Wings Of The Dove.txt
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/ange/opt/anaconda3/envs/NLP/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "wordclouds_main.py", line 134, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "wordclouds_main.py", line 115, in run
    outputFiles = wordclouds_util.python_wordCloud(inputFilename, inputDir, outputDir, config_filename,  selectedImage,
  File "/Users/ange/Desktop/QTM 446W/NLP-Suite-current-stable/src/wordclouds_util.py", line 664, in python_wordCloud
    tempOutputfile=display_wordCloud(doc,inputDir,outputDir,combinedtext, doNotListIndividualFiles, transformed_image_mask, stopwords, collocation,prefer_horizontal, bg_image=img, bg_image_flag = use_contour_only, font = font, max_words = max_words)
  File "/Users/ange/Desktop/QTM 446W/NLP-Suite-current-stable/src/wordclouds_util.py", line 314, in display_wordCloud
    wordcloud = WordCloud(width = 800, height = 800,
  File "/Users/ange/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 639, in generate
    return self.generate_from_text(text)
  File "/Users/ange/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 621, in generate_from_text
    self.generate_from_frequencies(words)
  File "/Users/ange/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 453, in generate_from_frequencies
    self.generate_from_frequencies(dict(frequencies[:2]),
  File "/Users/ange/opt/anaconda3/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 508, in generate_from_frequencies
    box_size = draw.textsize(word, font=transposed_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'

**Comment by Emory-NLP** [comment]
Please, always upload a screenshot of the GUI you are running with the options you are using.

**Comment by AngelinaYing** [comment]
![WechatIMG560](https://github.com/NLP-Suite/NLP-Suite/assets/114373779/ad867097-5fe1-4215-8b0d-bc5f45ebea51)

![WechatIMG561](https://github.com/NLP-Suite/NLP-Suite/assets/114373779/5803cfda-7709-46d2-8a81-1efd04941272)

**Comment by Emory-NLP** [comment]
I run the same GUI and corpus and get no error.
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/9745a0f4-9320-4898-9f05-0eeac6eef3f8)

Can you please go to your NLP environment in prompt (conda activate NLP) and run the command
pip show wordcloud
Mine is Version: 1.8.2.2

**Comment by Emory-NLP** [comment]
Also try this:
pip uninstall pillow
pip install Pillow==9.5.0

**Comment by AngelinaYing** [comment]
Thank you so much! It's working now.

It seems that my wordcloud version is correct (1.8.2.2) but pillow's version is more than 10. I reinstalled and it worked. Thank you!

**Comment by sengaungsein** [comment]
Thank you. It works for me now. You need to close and open GUI again.
