### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'textsize' 

### ISSUE THREAD

**Issue by sengaungsein** [NLP-Suite/NLP-Suite#1378]
Started running STANZA and wordcloud at 1:11.

Please, be patient. Depending upon the number of documents processed this may take a few minutes.

Processing file 1/4 1935.txt
Processing file 2/4 1947.txt
Processing file 3/4 1974.txt
Processing file 4/4 2008.txt
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "wordclouds_main.py", line 134, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "wordclouds_main.py", line 115, in run
    outputFiles = wordclouds_util.python_wordCloud(inputFilename, inputDir, outputDir, config_filename,  selectedImage,
  File "/Users/senga/Documents/NLP-Suite-current-stable/src/wordclouds_util.py", line 664, in python_wordCloud
    tempOutputfile=display_wordCloud(doc,inputDir,outputDir,combinedtext, doNotListIndividualFiles, transformed_image_mask, stopwords, collocation,prefer_horizontal, bg_image=img, bg_image_flag = use_contour_only, font = font, max_words = max_words)
  File "/Users/senga/Documents/NLP-Suite-current-stable/src/wordclouds_util.py", line 314, in display_wordCloud
    wordcloud = WordCloud(width = 800, height = 800,
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 639, in generate
    return self.generate_from_text(text)
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 621, in generate_from_text
    self.generate_from_frequencies(words)
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 453, in generate_from_frequencies
    self.generate_from_frequencies(dict(frequencies[:2]),
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 508, in generate_from_frequencies
    box_size = draw.textsize(word, font=transposed_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'

**Comment by sgluong** [comment]
I am having the same issue. It looks like this is the same problem as #1374 and #1372 as well.

**Comment by sgluong** [comment]
I had the same issue. It looks like there are some suggestions on how to fix it on #1372
