### ISSUE TITLE
NLP Suite Mallet Topic Modelling 

### ISSUE THREAD

**Issue by sengaungsein** [NLP-Suite/NLP-Suite#1434]
Finished running MALLET Topic modeling at  23:23 taking 24 seconds.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "topic_modeling_main.py", line 105, in <lambda>
    run_script_command = lambda: run(GUI_util.input_main_dir_path.get(),
  File "topic_modeling_main.py", line 96, in run
    filesToOpen = topic_modeling_mallet_util.run_MALLET(inputDir, outputDir, openOutputFiles, chartPackage, dataTransformation,
  File "/Users/senga/Documents/NLP-Suite-current-stable/src/topic_modeling_mallet_util.py", line 327, in run_MALLET
    outputFiles = charts_matplotlib_seaborn_util.MALLET_heatmap(Composition_FileName, Keys_FileName, outputDir, fig_set={"figure.figsize": (8, 6), "figure.dpi": 300},
  File "/Users/senga/Documents/NLP-Suite-current-stable/src/charts_matplotlib_seaborn_util.py", line 53, in MALLET_heatmap
    heatmap = sns.heatmap(composition.iloc[:, 1:].map(float),  # Select all columns excluding index column
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'map'

**Comment by sengaungsein** [comment]
Thank you, professor. It walks now.
